CREATE TABLE IF NOT EXISTS public.tuition_records (
                                                      id int4 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                                      student_id int4 NOT NULL,
                                                      semester_id int4 NOT NULL,
                                                      total_amount numeric(12,2) NOT NULL,
    paid_amount numeric(12,2) NOT NULL DEFAULT 0,
    status varchar(50) NOT NULL,
    due_date date,
    note varchar(500),
    created_at timestamp(6),
    updated_at timestamp(6),
    CONSTRAINT fk_tuition_records_student
    FOREIGN KEY (student_id) REFERENCES public.students(id),
    CONSTRAINT fk_tuition_records_semester
    FOREIGN KEY (semester_id) REFERENCES public.semesters(id),
    CONSTRAINT tuition_records_status_check CHECK (
                                                      status IN ('PAID', 'OWED', 'PARTIAL', 'WAIVED')
    ),
    CONSTRAINT tuition_records_total_amount_check CHECK (total_amount >= 0),
    CONSTRAINT tuition_records_paid_amount_check CHECK (paid_amount >= 0),
    CONSTRAINT tuition_records_paid_not_over_total_check CHECK (paid_amount <= total_amount)
    );

CREATE UNIQUE INDEX IF NOT EXISTS uk_tuition_records_student_semester
    ON public.tuition_records(student_id, semester_id);

CREATE INDEX IF NOT EXISTS idx_tuition_records_student_id
    ON public.tuition_records(student_id);

CREATE INDEX IF NOT EXISTS idx_tuition_records_semester_id
    ON public.tuition_records(semester_id);

CREATE INDEX IF NOT EXISTS idx_tuition_records_status
    ON public.tuition_records(status);
