CREATE TABLE IF NOT EXISTS public.attendances (
                                                  id int4 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                                  course_section_id int4 NOT NULL,
                                                  student_id int4 NOT NULL,
                                                  attendance_date date NOT NULL,
                                                  status varchar(50) NOT NULL,
    note varchar(500),
    recorded_by_user_id int4,
    created_at timestamp(6),
    updated_at timestamp(6),
    CONSTRAINT fk_attendances_course_section
    FOREIGN KEY (course_section_id) REFERENCES public.course_sections(id),
    CONSTRAINT fk_attendances_student
    FOREIGN KEY (student_id) REFERENCES public.students(id),
    CONSTRAINT fk_attendances_recorded_by_user
    FOREIGN KEY (recorded_by_user_id) REFERENCES public.users(id),
    CONSTRAINT attendances_status_check CHECK (
                                                  status IN ('PRESENT', 'ABSENT', 'LATE', 'EXCUSED')
    )
    );

CREATE UNIQUE INDEX IF NOT EXISTS uk_attendances_section_student_date
    ON public.attendances(course_section_id, student_id, attendance_date);

CREATE INDEX IF NOT EXISTS idx_attendances_course_section_date
    ON public.attendances(course_section_id, attendance_date);

CREATE INDEX IF NOT EXISTS idx_attendances_student_id
    ON public.attendances(student_id);

CREATE TABLE IF NOT EXISTS public.class_announcements (
                                                          id int4 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                                          course_section_id int4 NOT NULL,
                                                          lecturer_id int4 NOT NULL,
                                                          title varchar(255) NOT NULL,
    content varchar(2000) NOT NULL,
    created_at timestamp(6),
    CONSTRAINT fk_class_announcements_course_section
    FOREIGN KEY (course_section_id) REFERENCES public.course_sections(id),
    CONSTRAINT fk_class_announcements_lecturer
    FOREIGN KEY (lecturer_id) REFERENCES public.lecturers(id)
    );

CREATE INDEX IF NOT EXISTS idx_class_announcements_course_section_id
    ON public.class_announcements(course_section_id);

CREATE TABLE IF NOT EXISTS public.notifications (
                                                    id int4 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                                    recipient_user_id int4 NOT NULL,
                                                    announcement_id int4,
                                                    title varchar(255) NOT NULL,
    content varchar(2000) NOT NULL,
    is_read boolean NOT NULL DEFAULT false,
    read_at timestamp(6),
    created_at timestamp(6),
    CONSTRAINT fk_notifications_recipient_user
    FOREIGN KEY (recipient_user_id) REFERENCES public.users(id),
    CONSTRAINT fk_notifications_announcement
    FOREIGN KEY (announcement_id) REFERENCES public.class_announcements(id)
    );

CREATE INDEX IF NOT EXISTS idx_notifications_recipient_user_id
    ON public.notifications(recipient_user_id);

CREATE INDEX IF NOT EXISTS idx_notifications_recipient_read
    ON public.notifications(recipient_user_id, is_read);
