CREATE TABLE IF NOT EXISTS public.payment_transactions (
                                                           id int4 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                                           transaction_code varchar(100) NOT NULL UNIQUE,
    tuition_record_id int4 NOT NULL,
    student_id int4 NOT NULL,
    amount numeric(12,2) NOT NULL,
    provider varchar(50) NOT NULL,
    status varchar(50) NOT NULL,
    payment_url varchar(500),
    provider_reference varchar(255),
    failure_reason varchar(500),
    created_at timestamp(6),
    completed_at timestamp(6),
    updated_at timestamp(6),
    CONSTRAINT fk_payment_transactions_tuition_record
    FOREIGN KEY (tuition_record_id) REFERENCES public.tuition_records(id),
    CONSTRAINT fk_payment_transactions_student
    FOREIGN KEY (student_id) REFERENCES public.students(id),
    CONSTRAINT payment_transactions_provider_check CHECK (
                                                             provider IN ('MOCK')
    ),
    CONSTRAINT payment_transactions_status_check CHECK (
                                                           status IN ('PENDING', 'SUCCESS', 'FAILED', 'CANCELLED')
    ),
    CONSTRAINT payment_transactions_amount_check CHECK (amount > 0)
    );

CREATE INDEX IF NOT EXISTS idx_payment_transactions_student_id
    ON public.payment_transactions(student_id);

CREATE INDEX IF NOT EXISTS idx_payment_transactions_tuition_record_id
    ON public.payment_transactions(tuition_record_id);

CREATE INDEX IF NOT EXISTS idx_payment_transactions_status
    ON public.payment_transactions(status);
