-- V1__init_schema.sql

CREATE SCHEMA IF NOT EXISTS public AUTHORIZATION "QLSV_user";

-- permissions
CREATE TABLE IF NOT EXISTS public.permissions (
                                                  id int4 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                                  description varchar(255),
    "name" varchar(255) NOT NULL,
    CONSTRAINT permissions_name_check CHECK (
(name)::text = ANY (
    (ARRAY[
     'VIEW_STUDENT'::character varying,
     'CREATE_STUDENT'::character varying,
     'UPDATE_STUDENT'::character varying,
     'DELETE_STUDENT'::character varying,
     'CHANGE_PASSWORD'::character varying
    ])::text[]
    )
    ),
    CONSTRAINT permissions_pkey PRIMARY KEY (id),
    CONSTRAINT ukpnvtwliis6p05pn6i3ndjrqt2 UNIQUE (name)
    );

-- roles
CREATE TABLE IF NOT EXISTS public.roles (
                                            id int4 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                            created_at timestamp(6),
    description varchar(255),
    "name" varchar(255) NOT NULL,
    CONSTRAINT roles_name_check CHECK (
(name)::text = ANY (
    (ARRAY[
     'ADMIN'::character varying,
     'STUDENT'::character varying,
     'TEACHER'::character varying
    ])::text[]
    )
    ),
    CONSTRAINT roles_pkey PRIMARY KEY (id),
    CONSTRAINT ukofx66keruapi6vyqpv6f2or37 UNIQUE (name)
    );

-- users
CREATE TABLE IF NOT EXISTS public.users (
                                            id int4 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                            created_at timestamp(6),
    email varchar(255) NOT NULL,
    full_name varchar(255),
    is_active bool,
    password_hash varchar(255) NOT NULL,
    updated_at timestamp(6),
    username varchar(255) NOT NULL,
    CONSTRAINT users_pkey PRIMARY KEY (id),
    CONSTRAINT uk6dotkott2kjsp8vw4d0m25fb7 UNIQUE (email),
    CONSTRAINT ukr43af9ap4edm43mmtq01oddj6 UNIQUE (username)
    );

-- students
CREATE TABLE IF NOT EXISTS public.students (
                                               id int4 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                               created_at timestamp(6),
    date_of_birth date,
    email varchar(255),
    full_name varchar(255),
    phone varchar(255),
    student_code varchar(255) NOT NULL,
    user_id int4,
    CONSTRAINT students_pkey PRIMARY KEY (id),
    CONSTRAINT ukcgcf3r5xk73o0etbduc1qxnol UNIQUE (student_code),
    CONSTRAINT ukg4fwvutq09fjdlb4bb0byp7t UNIQUE (user_id)
    );

-- role_permissions
CREATE TABLE IF NOT EXISTS public.role_permissions (
                                                       role_id int4 NOT NULL,
                                                       permission_id int4 NOT NULL,
                                                       CONSTRAINT role_permissions_pkey PRIMARY KEY (role_id, permission_id)
    );

-- user_roles
CREATE TABLE IF NOT EXISTS public.user_roles (
                                                 user_id int4 NOT NULL,
                                                 role_id int4 NOT NULL,
                                                 CONSTRAINT user_roles_pkey PRIMARY KEY (user_id, role_id)
    );

-- Foreign keys
ALTER TABLE public.students
    ADD CONSTRAINT fk_students_user
        FOREIGN KEY (user_id) REFERENCES public.users (id);

ALTER TABLE public.role_permissions
    ADD CONSTRAINT fk_role_permissions_role
        FOREIGN KEY (role_id) REFERENCES public.roles (id);

ALTER TABLE public.role_permissions
    ADD CONSTRAINT fk_role_permissions_permission
        FOREIGN KEY (permission_id) REFERENCES public.permissions (id);

ALTER TABLE public.user_roles
    ADD CONSTRAINT fk_user_roles_user
        FOREIGN KEY (user_id) REFERENCES public.users (id);

ALTER TABLE public.user_roles
    ADD CONSTRAINT fk_user_roles_role
        FOREIGN KEY (role_id) REFERENCES public.roles (id);


-- Seed roles
INSERT INTO roles (name, description, created_at)
VALUES
    ('ADMIN', 'System admin', now()),
    ('STUDENT', 'Student role', now()),
    ('TEACHER', 'Teacher role', now())
    ON CONFLICT (name) DO NOTHING;

-- Seed admin user (password BCrypt)
INSERT INTO users (username, email, password_hash, full_name, is_active, created_at, updated_at)
VALUES (
           'admin',
           'admin@example.com',
           '$2a$12$R3Q7ZRItTF8Ht6ny4Qo4JuwqG2unlVsnzDw2odpqCp7ggyX5lbj76',
           'Admin',
           true,
           now(),
           now()
       )
    ON CONFLICT (username) DO NOTHING;

-- Assign ADMIN role to admin
INSERT INTO user_roles (user_id, role_id)
SELECT u.id, r.id
FROM users u, roles r
WHERE u.username = 'admin' AND r.name = 'ADMIN'
    ON CONFLICT DO NOTHING;