CREATE TABLE IF NOT EXISTS public.lecturers (
                                                id int4 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                                user_id int4 NOT NULL,
                                                lecturer_code varchar(255) NOT NULL,
    full_name varchar(255),
    email varchar(255),
    phone varchar(255),
    department varchar(255),
    created_at timestamp(6),
    CONSTRAINT lecturers_pkey PRIMARY KEY (id),
    CONSTRAINT uk_lecturers_user UNIQUE (user_id),
    CONSTRAINT uk_lecturers_code UNIQUE (lecturer_code),
    CONSTRAINT fk_lecturers_user FOREIGN KEY (user_id) REFERENCES public.users(id)
    );

CREATE TABLE IF NOT EXISTS public.academic_advisors (
                                                        id int4 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                                        user_id int4 NOT NULL,
                                                        advisor_code varchar(255) NOT NULL,
    full_name varchar(255),
    email varchar(255),
    phone varchar(255),
    department varchar(255),
    created_at timestamp(6),
    CONSTRAINT academic_advisors_pkey PRIMARY KEY (id),
    CONSTRAINT uk_academic_advisors_user UNIQUE (user_id),
    CONSTRAINT uk_academic_advisors_code UNIQUE (advisor_code),
    CONSTRAINT fk_academic_advisors_user FOREIGN KEY (user_id) REFERENCES public.users(id)
    );