CREATE TABLE IF NOT EXISTS public.departments (
                                                  id int4 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                                  code varchar(50) NOT NULL UNIQUE,
    name varchar(255) NOT NULL,
    description varchar(500),
    created_at timestamp(6)
    );

CREATE TABLE IF NOT EXISTS public.programs (
                                               id int4 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                               department_id int4 NOT NULL,
                                               code varchar(50) NOT NULL UNIQUE,
    name varchar(255) NOT NULL,
    degree_level varchar(100),
    duration_years int4,
    description varchar(500),
    created_at timestamp(6),
    CONSTRAINT fk_programs_department FOREIGN KEY (department_id) REFERENCES public.departments(id)
    );

CREATE TABLE IF NOT EXISTS public.courses (
                                              id int4 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                              department_id int4 NOT NULL,
                                              code varchar(50) NOT NULL UNIQUE,
    name varchar(255) NOT NULL,
    credits int4 NOT NULL,
    description varchar(500),
    is_active bool,
    created_at timestamp(6),
    CONSTRAINT fk_courses_department FOREIGN KEY (department_id) REFERENCES public.departments(id),
    CONSTRAINT courses_credits_check CHECK (credits > 0)
    );

CREATE TABLE IF NOT EXISTS public.course_prerequisites (
                                                           course_id int4 NOT NULL,
                                                           prerequisite_course_id int4 NOT NULL,
                                                           CONSTRAINT course_prerequisites_pkey PRIMARY KEY (course_id, prerequisite_course_id),
    CONSTRAINT fk_course_prerequisites_course FOREIGN KEY (course_id) REFERENCES public.courses(id),
    CONSTRAINT fk_course_prerequisites_prerequisite FOREIGN KEY (prerequisite_course_id) REFERENCES public.courses(id),
    CONSTRAINT course_prerequisites_not_self CHECK (course_id <> prerequisite_course_id)
    );