CREATE TABLE IF NOT EXISTS public.semesters (
                                                id int4 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                                code varchar(50) NOT NULL UNIQUE,
    name varchar(255) NOT NULL,
    start_date date NOT NULL,
    end_date date NOT NULL,
    exam_start_date date,
    exam_end_date date,
    status varchar(50) NOT NULL,
    created_at timestamp(6),
    CONSTRAINT semesters_status_check CHECK (
                                                status IN ('UPCOMING', 'ACTIVE', 'COMPLETED')
    ),
    CONSTRAINT semesters_date_check CHECK (
                                              start_date <= end_date
                                          ),
    CONSTRAINT semesters_exam_date_check CHECK (
                                                   exam_start_date IS NULL
                                                   OR exam_end_date IS NULL
                                                   OR exam_start_date <= exam_end_date
                                               )
    );

CREATE TABLE IF NOT EXISTS public.rooms (
                                            id int4 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                            code varchar(50) NOT NULL UNIQUE,
    name varchar(255) NOT NULL,
    building varchar(255),
    capacity int4,
    is_active bool,
    created_at timestamp(6),
    CONSTRAINT rooms_capacity_check CHECK (
                                              capacity IS NULL OR capacity > 0
                                          )
    );

CREATE TABLE IF NOT EXISTS public.course_sections (
                                                      id int4 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                                      code varchar(50) NOT NULL UNIQUE,
    course_id int4 NOT NULL,
    lecturer_id int4 NOT NULL,
    semester_id int4 NOT NULL,
    capacity int4 NOT NULL,
    enrolled_count int4 NOT NULL DEFAULT 0,
    status varchar(50) NOT NULL,
    created_at timestamp(6),
    CONSTRAINT fk_course_sections_course
    FOREIGN KEY (course_id) REFERENCES public.courses(id),
    CONSTRAINT fk_course_sections_lecturer
    FOREIGN KEY (lecturer_id) REFERENCES public.lecturers(id),
    CONSTRAINT fk_course_sections_semester
    FOREIGN KEY (semester_id) REFERENCES public.semesters(id),
    CONSTRAINT course_sections_capacity_check CHECK (
                                                        capacity > 0
                                                    ),
    CONSTRAINT course_sections_enrolled_count_check CHECK (
                                                              enrolled_count >= 0 AND enrolled_count <= capacity
                                                          ),
    CONSTRAINT course_sections_status_check CHECK (
                                                      status IN ('DRAFT', 'OPEN', 'CLOSED', 'CANCELLED')
    )
    );

CREATE TABLE IF NOT EXISTS public.course_section_schedules (
                                                               id int4 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                                               course_section_id int4 NOT NULL,
                                                               room_id int4 NOT NULL,
                                                               day_of_week int4 NOT NULL,
                                                               start_time time NOT NULL,
                                                               end_time time NOT NULL,
                                                               CONSTRAINT fk_course_section_schedules_section
                                                               FOREIGN KEY (course_section_id) REFERENCES public.course_sections(id),
    CONSTRAINT fk_course_section_schedules_room
    FOREIGN KEY (room_id) REFERENCES public.rooms(id),
    CONSTRAINT course_section_schedules_day_check CHECK (
                                                            day_of_week BETWEEN 1 AND 7
                                                        ),
    CONSTRAINT course_section_schedules_time_check CHECK (
                                                             start_time < end_time
                                                         )
    );

CREATE INDEX IF NOT EXISTS idx_course_sections_course_id
    ON public.course_sections(course_id);

CREATE INDEX IF NOT EXISTS idx_course_sections_lecturer_id
    ON public.course_sections(lecturer_id);

CREATE INDEX IF NOT EXISTS idx_course_sections_semester_id
    ON public.course_sections(semester_id);

CREATE INDEX IF NOT EXISTS idx_course_section_schedules_section_id
    ON public.course_section_schedules(course_section_id);

CREATE INDEX IF NOT EXISTS idx_course_section_schedules_room_day_time
    ON public.course_section_schedules(room_id, day_of_week, start_time, end_time);