ALTER TABLE public.students
    ADD COLUMN IF NOT EXISTS academic_status varchar(50) NOT NULL DEFAULT 'STUDYING';

ALTER TABLE public.students
DROP CONSTRAINT IF EXISTS students_academic_status_check;

ALTER TABLE public.students
    ADD CONSTRAINT students_academic_status_check CHECK (
        academic_status IN ('STUDYING', 'ON_LEAVE', 'GRADUATED', 'SUSPENDED')
        );

CREATE TABLE IF NOT EXISTS public.enrollments (
                                                  id int4 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                                  student_id int4 NOT NULL,
                                                  course_section_id int4 NOT NULL,
                                                  status varchar(50) NOT NULL,
    enrolled_at timestamp(6),
    updated_at timestamp(6),
    CONSTRAINT fk_enrollments_student
    FOREIGN KEY (student_id) REFERENCES public.students(id),
    CONSTRAINT fk_enrollments_course_section
    FOREIGN KEY (course_section_id) REFERENCES public.course_sections(id),
    CONSTRAINT enrollments_status_check CHECK (
                                                  status IN ('ENROLLED', 'DROPPED', 'WAITLISTED', 'PASSED', 'FAILED')
    )
    );

CREATE UNIQUE INDEX IF NOT EXISTS uk_enrollments_student_section
    ON public.enrollments(student_id, course_section_id);

CREATE INDEX IF NOT EXISTS idx_enrollments_student_id
    ON public.enrollments(student_id);

CREATE INDEX IF NOT EXISTS idx_enrollments_course_section_id
    ON public.enrollments(course_section_id);