
CREATE TABLE IF NOT EXISTS public.enrollment_grades (
                                                        id int4 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                                        enrollment_id int4 NOT NULL UNIQUE,
                                                        process_score numeric(4,1),
    midterm_score numeric(4,1),
    final_score numeric(4,1),
    total_score numeric(4,1),
    status varchar(50) NOT NULL DEFAULT 'DRAFT',
    published_at timestamp(6),
    created_at timestamp(6),
    updated_at timestamp(6),
    CONSTRAINT fk_enrollment_grades_enrollment
    FOREIGN KEY (enrollment_id) REFERENCES public.enrollments(id),
    CONSTRAINT enrollment_grades_status_check CHECK (status IN ('DRAFT', 'PUBLISHED')),
    CONSTRAINT enrollment_grades_process_score_check CHECK (process_score IS NULL OR (process_score >= 0 AND process_score <= 10)),
    CONSTRAINT enrollment_grades_midterm_score_check CHECK (midterm_score IS NULL OR (midterm_score >= 0 AND midterm_score <= 10)),
    CONSTRAINT enrollment_grades_final_score_check CHECK (final_score IS NULL OR (final_score >= 0 AND final_score <= 10)),
    CONSTRAINT enrollment_grades_total_score_check CHECK (total_score IS NULL OR (total_score >= 0 AND total_score <= 10))
    );

CREATE TABLE IF NOT EXISTS public.grade_unlock_requests (
                                                            id int4 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                                            grade_id int4 NOT NULL,
                                                            lecturer_id int4 NOT NULL,
                                                            reason varchar(500) NOT NULL,
    status varchar(50) NOT NULL,
    reviewer_note varchar(500),
    created_at timestamp(6),
    reviewed_at timestamp(6),
    CONSTRAINT fk_grade_unlock_requests_grade
    FOREIGN KEY (grade_id) REFERENCES public.enrollment_grades(id),
    CONSTRAINT fk_grade_unlock_requests_lecturer
    FOREIGN KEY (lecturer_id) REFERENCES public.lecturers(id),
    CONSTRAINT grade_unlock_requests_status_check CHECK (status IN ('PENDING', 'APPROVED', 'REJECTED'))
    );

CREATE TABLE IF NOT EXISTS public.audit_logs (
                                                 id int4 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                                 actor_username varchar(255),
    action varchar(255) NOT NULL,
    target_type varchar(255),
    target_id int4,
    details varchar(1000),
    created_at timestamp(6)
    );

CREATE INDEX IF NOT EXISTS idx_enrollment_grades_enrollment_id
    ON public.enrollment_grades(enrollment_id);

CREATE INDEX IF NOT EXISTS idx_grade_unlock_requests_status
    ON public.grade_unlock_requests(status);

CREATE INDEX IF NOT EXISTS idx_audit_logs_target
    ON public.audit_logs(target_type, target_id);