CREATE TABLE IF NOT EXISTS public.advisor_students (
                                                       advisor_id int4 NOT NULL,
                                                       student_id int4 NOT NULL,
                                                       assigned_at timestamp(6),
    CONSTRAINT advisor_students_pkey PRIMARY KEY (advisor_id, student_id),
    CONSTRAINT fk_advisor_students_advisor
    FOREIGN KEY (advisor_id) REFERENCES public.academic_advisors(id),
    CONSTRAINT fk_advisor_students_student
    FOREIGN KEY (student_id) REFERENCES public.students(id)
    );

CREATE TABLE IF NOT EXISTS public.academic_requests (
                                                        id int4 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                                        student_id int4 NOT NULL,
                                                        advisor_id int4,
                                                        type varchar(50) NOT NULL,
    title varchar(255) NOT NULL,
    content varchar(1000) NOT NULL,
    attachment_url varchar(500),
    status varchar(50) NOT NULL,
    advisor_note varchar(500),
    created_at timestamp(6),
    reviewed_at timestamp(6),
    CONSTRAINT fk_academic_requests_student
    FOREIGN KEY (student_id) REFERENCES public.students(id),
    CONSTRAINT fk_academic_requests_advisor
    FOREIGN KEY (advisor_id) REFERENCES public.academic_advisors(id),
    CONSTRAINT academic_requests_type_check CHECK (
                                                      type IN ('LEAVE_OF_ABSENCE', 'GRADE_REVIEW', 'CREDIT_OVERLOAD', 'OTHER')
    ),
    CONSTRAINT academic_requests_status_check CHECK (
                                                        status IN ('PENDING', 'APPROVED', 'REJECTED')
    )
    );

CREATE INDEX IF NOT EXISTS idx_advisor_students_student_id
    ON public.advisor_students(student_id);

CREATE INDEX IF NOT EXISTS idx_academic_requests_student_id
    ON public.academic_requests(student_id);

CREATE INDEX IF NOT EXISTS idx_academic_requests_advisor_id
    ON public.academic_requests(advisor_id);

CREATE INDEX IF NOT EXISTS idx_academic_requests_status
    ON public.academic_requests(status);