-- Full backend schema snapshot.
-- For documentation/manual setup only. The application should normally use Flyway migrations V1..V12.
-- This script intentionally does not create flyway_schema_history and does not seed the admin user.

CREATE SCHEMA IF NOT EXISTS public;

CREATE TABLE IF NOT EXISTS public.permissions (
    id int4 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    description varchar(255),
    "name" varchar(255) NOT NULL UNIQUE,
    CONSTRAINT permissions_name_check CHECK (
        "name" IN ('VIEW_STUDENT', 'CREATE_STUDENT', 'UPDATE_STUDENT', 'DELETE_STUDENT', 'CHANGE_PASSWORD')
    )
);

CREATE TABLE IF NOT EXISTS public.roles (
    id int4 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp(6),
    description varchar(255),
    "name" varchar(255) NOT NULL UNIQUE,
    CONSTRAINT roles_name_check CHECK (
        "name" IN ('ADMIN', 'STUDENT', 'LECTURER', 'ACADEMIC_ADVISOR')
    )
);

CREATE TABLE IF NOT EXISTS public.users (
    id int4 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp(6),
    email varchar(255) NOT NULL UNIQUE,
    full_name varchar(255),
    is_active bool,
    password_hash varchar(255) NOT NULL,
    updated_at timestamp(6),
    username varchar(255) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS public.students (
    id int4 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp(6),
    date_of_birth date,
    email varchar(255),
    full_name varchar(255),
    phone varchar(255),
    student_code varchar(255) NOT NULL UNIQUE,
    user_id int4 UNIQUE,
    academic_status varchar(50) NOT NULL DEFAULT 'STUDYING',
    CONSTRAINT fk_students_user FOREIGN KEY (user_id) REFERENCES public.users(id),
    CONSTRAINT students_academic_status_check CHECK (
        academic_status IN ('STUDYING', 'ON_LEAVE', 'GRADUATED', 'SUSPENDED')
    )
);

CREATE TABLE IF NOT EXISTS public.role_permissions (
    role_id int4 NOT NULL,
    permission_id int4 NOT NULL,
    CONSTRAINT role_permissions_pkey PRIMARY KEY (role_id, permission_id),
    CONSTRAINT fk_role_permissions_role FOREIGN KEY (role_id) REFERENCES public.roles(id),
    CONSTRAINT fk_role_permissions_permission FOREIGN KEY (permission_id) REFERENCES public.permissions(id)
);

CREATE TABLE IF NOT EXISTS public.user_roles (
    user_id int4 NOT NULL,
    role_id int4 NOT NULL,
    CONSTRAINT user_roles_pkey PRIMARY KEY (user_id, role_id),
    CONSTRAINT fk_user_roles_user FOREIGN KEY (user_id) REFERENCES public.users(id),
    CONSTRAINT fk_user_roles_role FOREIGN KEY (role_id) REFERENCES public.roles(id)
);

CREATE TABLE IF NOT EXISTS public.lecturers (
    id int4 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id int4 NOT NULL UNIQUE,
    lecturer_code varchar(255) NOT NULL UNIQUE,
    full_name varchar(255),
    email varchar(255),
    phone varchar(255),
    department varchar(255),
    created_at timestamp(6),
    CONSTRAINT fk_lecturers_user FOREIGN KEY (user_id) REFERENCES public.users(id)
);

CREATE TABLE IF NOT EXISTS public.academic_advisors (
    id int4 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id int4 NOT NULL UNIQUE,
    advisor_code varchar(255) NOT NULL UNIQUE,
    full_name varchar(255),
    email varchar(255),
    phone varchar(255),
    department varchar(255),
    created_at timestamp(6),
    CONSTRAINT fk_academic_advisors_user FOREIGN KEY (user_id) REFERENCES public.users(id)
);

CREATE TABLE IF NOT EXISTS public.departments (
    id int4 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code varchar(50) NOT NULL UNIQUE,
    name varchar(255) NOT NULL,
    description varchar(500),
    created_at timestamp(6)
);

CREATE TABLE IF NOT EXISTS public.programs (
    id int4 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    department_id int4 NOT NULL,
    code varchar(50) NOT NULL UNIQUE,
    name varchar(255) NOT NULL,
    degree_level varchar(100),
    duration_years int4,
    description varchar(500),
    created_at timestamp(6),
    CONSTRAINT fk_programs_department FOREIGN KEY (department_id) REFERENCES public.departments(id)
);

CREATE TABLE IF NOT EXISTS public.courses (
    id int4 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    department_id int4 NOT NULL,
    code varchar(50) NOT NULL UNIQUE,
    name varchar(255) NOT NULL,
    credits int4 NOT NULL,
    description varchar(500),
    is_active bool,
    created_at timestamp(6),
    CONSTRAINT fk_courses_department FOREIGN KEY (department_id) REFERENCES public.departments(id),
    CONSTRAINT courses_credits_check CHECK (credits > 0)
);

CREATE TABLE IF NOT EXISTS public.course_prerequisites (
    course_id int4 NOT NULL,
    prerequisite_course_id int4 NOT NULL,
    CONSTRAINT course_prerequisites_pkey PRIMARY KEY (course_id, prerequisite_course_id),
    CONSTRAINT fk_course_prerequisites_course FOREIGN KEY (course_id) REFERENCES public.courses(id),
    CONSTRAINT fk_course_prerequisites_prerequisite FOREIGN KEY (prerequisite_course_id) REFERENCES public.courses(id),
    CONSTRAINT course_prerequisites_not_self CHECK (course_id <> prerequisite_course_id)
);

CREATE TABLE IF NOT EXISTS public.semesters (
    id int4 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code varchar(50) NOT NULL UNIQUE,
    name varchar(255) NOT NULL,
    start_date date NOT NULL,
    end_date date NOT NULL,
    exam_start_date date,
    exam_end_date date,
    status varchar(50) NOT NULL,
    created_at timestamp(6),
    CONSTRAINT semesters_status_check CHECK (status IN ('UPCOMING', 'ACTIVE', 'COMPLETED')),
    CONSTRAINT semesters_date_check CHECK (start_date <= end_date),
    CONSTRAINT semesters_exam_date_check CHECK (
        exam_start_date IS NULL OR exam_end_date IS NULL OR exam_start_date <= exam_end_date
    )
);

CREATE TABLE IF NOT EXISTS public.rooms (
    id int4 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code varchar(50) NOT NULL UNIQUE,
    name varchar(255) NOT NULL,
    building varchar(255),
    capacity int4,
    is_active bool,
    created_at timestamp(6),
    CONSTRAINT rooms_capacity_check CHECK (capacity IS NULL OR capacity > 0)
);

CREATE TABLE IF NOT EXISTS public.course_sections (
    id int4 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code varchar(50) NOT NULL UNIQUE,
    course_id int4 NOT NULL,
    lecturer_id int4 NOT NULL,
    semester_id int4 NOT NULL,
    capacity int4 NOT NULL,
    enrolled_count int4 NOT NULL DEFAULT 0,
    status varchar(50) NOT NULL,
    created_at timestamp(6),
    CONSTRAINT fk_course_sections_course FOREIGN KEY (course_id) REFERENCES public.courses(id),
    CONSTRAINT fk_course_sections_lecturer FOREIGN KEY (lecturer_id) REFERENCES public.lecturers(id),
    CONSTRAINT fk_course_sections_semester FOREIGN KEY (semester_id) REFERENCES public.semesters(id),
    CONSTRAINT course_sections_capacity_check CHECK (capacity > 0),
    CONSTRAINT course_sections_enrolled_count_check CHECK (enrolled_count >= 0 AND enrolled_count <= capacity),
    CONSTRAINT course_sections_status_check CHECK (status IN ('DRAFT', 'OPEN', 'CLOSED', 'CANCELLED'))
);

CREATE TABLE IF NOT EXISTS public.course_section_schedules (
    id int4 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_section_id int4 NOT NULL,
    room_id int4 NOT NULL,
    day_of_week int4 NOT NULL,
    start_time time NOT NULL,
    end_time time NOT NULL,
    CONSTRAINT fk_course_section_schedules_section FOREIGN KEY (course_section_id) REFERENCES public.course_sections(id),
    CONSTRAINT fk_course_section_schedules_room FOREIGN KEY (room_id) REFERENCES public.rooms(id),
    CONSTRAINT course_section_schedules_day_check CHECK (day_of_week BETWEEN 1 AND 7),
    CONSTRAINT course_section_schedules_time_check CHECK (start_time < end_time)
);

CREATE TABLE IF NOT EXISTS public.enrollments (
    id int4 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id int4 NOT NULL,
    course_section_id int4 NOT NULL,
    status varchar(50) NOT NULL,
    enrolled_at timestamp(6),
    updated_at timestamp(6),
    CONSTRAINT fk_enrollments_student FOREIGN KEY (student_id) REFERENCES public.students(id),
    CONSTRAINT fk_enrollments_course_section FOREIGN KEY (course_section_id) REFERENCES public.course_sections(id),
    CONSTRAINT enrollments_status_check CHECK (
        status IN ('ENROLLED', 'DROPPED', 'WAITLISTED', 'PASSED', 'FAILED')
    )
);

CREATE TABLE IF NOT EXISTS public.enrollment_grades (
    id int4 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    enrollment_id int4 NOT NULL UNIQUE,
    process_score numeric(4,1),
    midterm_score numeric(4,1),
    final_score numeric(4,1),
    total_score numeric(4,1),
    status varchar(50) NOT NULL DEFAULT 'DRAFT',
    published_at timestamp(6),
    created_at timestamp(6),
    updated_at timestamp(6),
    CONSTRAINT fk_enrollment_grades_enrollment FOREIGN KEY (enrollment_id) REFERENCES public.enrollments(id),
    CONSTRAINT enrollment_grades_status_check CHECK (status IN ('DRAFT', 'PUBLISHED')),
    CONSTRAINT enrollment_grades_process_score_check CHECK (process_score IS NULL OR (process_score >= 0 AND process_score <= 10)),
    CONSTRAINT enrollment_grades_midterm_score_check CHECK (midterm_score IS NULL OR (midterm_score >= 0 AND midterm_score <= 10)),
    CONSTRAINT enrollment_grades_final_score_check CHECK (final_score IS NULL OR (final_score >= 0 AND final_score <= 10)),
    CONSTRAINT enrollment_grades_total_score_check CHECK (total_score IS NULL OR (total_score >= 0 AND total_score <= 10))
);

CREATE TABLE IF NOT EXISTS public.grade_unlock_requests (
    id int4 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    grade_id int4 NOT NULL,
    lecturer_id int4 NOT NULL,
    reason varchar(500) NOT NULL,
    status varchar(50) NOT NULL,
    reviewer_note varchar(500),
    created_at timestamp(6),
    reviewed_at timestamp(6),
    CONSTRAINT fk_grade_unlock_requests_grade FOREIGN KEY (grade_id) REFERENCES public.enrollment_grades(id),
    CONSTRAINT fk_grade_unlock_requests_lecturer FOREIGN KEY (lecturer_id) REFERENCES public.lecturers(id),
    CONSTRAINT grade_unlock_requests_status_check CHECK (status IN ('PENDING', 'APPROVED', 'REJECTED'))
);

CREATE TABLE IF NOT EXISTS public.audit_logs (
    id int4 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_username varchar(255),
    action varchar(255) NOT NULL,
    target_type varchar(255),
    target_id int4,
    details varchar(1000),
    created_at timestamp(6)
);

CREATE TABLE IF NOT EXISTS public.advisor_students (
    advisor_id int4 NOT NULL,
    student_id int4 NOT NULL,
    assigned_at timestamp(6),
    CONSTRAINT advisor_students_pkey PRIMARY KEY (advisor_id, student_id),
    CONSTRAINT fk_advisor_students_advisor FOREIGN KEY (advisor_id) REFERENCES public.academic_advisors(id),
    CONSTRAINT fk_advisor_students_student FOREIGN KEY (student_id) REFERENCES public.students(id)
);

CREATE TABLE IF NOT EXISTS public.academic_requests (
    id int4 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id int4 NOT NULL,
    advisor_id int4,
    type varchar(50) NOT NULL,
    title varchar(255) NOT NULL,
    content varchar(1000) NOT NULL,
    attachment_url varchar(500),
    status varchar(50) NOT NULL,
    advisor_note varchar(500),
    created_at timestamp(6),
    reviewed_at timestamp(6),
    CONSTRAINT fk_academic_requests_student FOREIGN KEY (student_id) REFERENCES public.students(id),
    CONSTRAINT fk_academic_requests_advisor FOREIGN KEY (advisor_id) REFERENCES public.academic_advisors(id),
    CONSTRAINT academic_requests_type_check CHECK (
        type IN ('LEAVE_OF_ABSENCE', 'GRADE_REVIEW', 'CREDIT_OVERLOAD', 'OTHER')
    ),
    CONSTRAINT academic_requests_status_check CHECK (status IN ('PENDING', 'APPROVED', 'REJECTED'))
);

CREATE TABLE IF NOT EXISTS public.tuition_records (
    id int4 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id int4 NOT NULL,
    semester_id int4 NOT NULL,
    total_amount numeric(12,2) NOT NULL,
    paid_amount numeric(12,2) NOT NULL DEFAULT 0,
    status varchar(50) NOT NULL,
    due_date date,
    note varchar(500),
    created_at timestamp(6),
    updated_at timestamp(6),
    CONSTRAINT fk_tuition_records_student FOREIGN KEY (student_id) REFERENCES public.students(id),
    CONSTRAINT fk_tuition_records_semester FOREIGN KEY (semester_id) REFERENCES public.semesters(id),
    CONSTRAINT tuition_records_status_check CHECK (status IN ('PAID', 'OWED', 'PARTIAL', 'WAIVED')),
    CONSTRAINT tuition_records_total_amount_check CHECK (total_amount >= 0),
    CONSTRAINT tuition_records_paid_amount_check CHECK (paid_amount >= 0),
    CONSTRAINT tuition_records_paid_not_over_total_check CHECK (paid_amount <= total_amount)
);

CREATE TABLE IF NOT EXISTS public.attendances (
    id int4 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_section_id int4 NOT NULL,
    student_id int4 NOT NULL,
    attendance_date date NOT NULL,
    status varchar(50) NOT NULL,
    note varchar(500),
    recorded_by_user_id int4,
    created_at timestamp(6),
    updated_at timestamp(6),
    CONSTRAINT fk_attendances_course_section FOREIGN KEY (course_section_id) REFERENCES public.course_sections(id),
    CONSTRAINT fk_attendances_student FOREIGN KEY (student_id) REFERENCES public.students(id),
    CONSTRAINT fk_attendances_recorded_by_user FOREIGN KEY (recorded_by_user_id) REFERENCES public.users(id),
    CONSTRAINT attendances_status_check CHECK (status IN ('PRESENT', 'ABSENT', 'LATE', 'EXCUSED'))
);

CREATE TABLE IF NOT EXISTS public.class_announcements (
    id int4 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_section_id int4 NOT NULL,
    lecturer_id int4 NOT NULL,
    title varchar(255) NOT NULL,
    content varchar(2000) NOT NULL,
    created_at timestamp(6),
    CONSTRAINT fk_class_announcements_course_section FOREIGN KEY (course_section_id) REFERENCES public.course_sections(id),
    CONSTRAINT fk_class_announcements_lecturer FOREIGN KEY (lecturer_id) REFERENCES public.lecturers(id)
);

CREATE TABLE IF NOT EXISTS public.notifications (
    id int4 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recipient_user_id int4 NOT NULL,
    announcement_id int4,
    title varchar(255) NOT NULL,
    content varchar(2000) NOT NULL,
    is_read boolean NOT NULL DEFAULT false,
    read_at timestamp(6),
    created_at timestamp(6),
    CONSTRAINT fk_notifications_recipient_user FOREIGN KEY (recipient_user_id) REFERENCES public.users(id),
    CONSTRAINT fk_notifications_announcement FOREIGN KEY (announcement_id) REFERENCES public.class_announcements(id)
);

CREATE TABLE IF NOT EXISTS public.payment_transactions (
    id int4 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transaction_code varchar(100) NOT NULL UNIQUE,
    tuition_record_id int4 NOT NULL,
    student_id int4 NOT NULL,
    amount numeric(12,2) NOT NULL,
    provider varchar(50) NOT NULL,
    status varchar(50) NOT NULL,
    payment_url varchar(500),
    provider_reference varchar(255),
    failure_reason varchar(500),
    created_at timestamp(6),
    completed_at timestamp(6),
    updated_at timestamp(6),
    CONSTRAINT fk_payment_transactions_tuition_record FOREIGN KEY (tuition_record_id) REFERENCES public.tuition_records(id),
    CONSTRAINT fk_payment_transactions_student FOREIGN KEY (student_id) REFERENCES public.students(id),
    CONSTRAINT payment_transactions_provider_check CHECK (provider IN ('MOCK')),
    CONSTRAINT payment_transactions_status_check CHECK (status IN ('PENDING', 'SUCCESS', 'FAILED', 'CANCELLED')),
    CONSTRAINT payment_transactions_amount_check CHECK (amount > 0)
);

CREATE INDEX IF NOT EXISTS idx_course_sections_course_id
    ON public.course_sections(course_id);

CREATE INDEX IF NOT EXISTS idx_course_sections_lecturer_id
    ON public.course_sections(lecturer_id);

CREATE INDEX IF NOT EXISTS idx_course_sections_semester_id
    ON public.course_sections(semester_id);

CREATE INDEX IF NOT EXISTS idx_course_section_schedules_section_id
    ON public.course_section_schedules(course_section_id);

CREATE INDEX IF NOT EXISTS idx_course_section_schedules_room_day_time
    ON public.course_section_schedules(room_id, day_of_week, start_time, end_time);

CREATE UNIQUE INDEX IF NOT EXISTS uk_enrollments_student_section
    ON public.enrollments(student_id, course_section_id);

CREATE INDEX IF NOT EXISTS idx_enrollments_student_id
    ON public.enrollments(student_id);

CREATE INDEX IF NOT EXISTS idx_enrollments_course_section_id
    ON public.enrollments(course_section_id);

CREATE INDEX IF NOT EXISTS idx_enrollment_grades_enrollment_id
    ON public.enrollment_grades(enrollment_id);

CREATE INDEX IF NOT EXISTS idx_grade_unlock_requests_status
    ON public.grade_unlock_requests(status);

CREATE INDEX IF NOT EXISTS idx_audit_logs_target
    ON public.audit_logs(target_type, target_id);

CREATE INDEX IF NOT EXISTS idx_advisor_students_student_id
    ON public.advisor_students(student_id);

CREATE INDEX IF NOT EXISTS idx_academic_requests_student_id
    ON public.academic_requests(student_id);

CREATE INDEX IF NOT EXISTS idx_academic_requests_advisor_id
    ON public.academic_requests(advisor_id);

CREATE INDEX IF NOT EXISTS idx_academic_requests_status
    ON public.academic_requests(status);

CREATE UNIQUE INDEX IF NOT EXISTS uk_tuition_records_student_semester
    ON public.tuition_records(student_id, semester_id);

CREATE INDEX IF NOT EXISTS idx_tuition_records_student_id
    ON public.tuition_records(student_id);

CREATE INDEX IF NOT EXISTS idx_tuition_records_semester_id
    ON public.tuition_records(semester_id);

CREATE INDEX IF NOT EXISTS idx_tuition_records_status
    ON public.tuition_records(status);

CREATE UNIQUE INDEX IF NOT EXISTS uk_attendances_section_student_date
    ON public.attendances(course_section_id, student_id, attendance_date);

CREATE INDEX IF NOT EXISTS idx_attendances_course_section_date
    ON public.attendances(course_section_id, attendance_date);

CREATE INDEX IF NOT EXISTS idx_attendances_student_id
    ON public.attendances(student_id);

CREATE INDEX IF NOT EXISTS idx_class_announcements_course_section_id
    ON public.class_announcements(course_section_id);

CREATE INDEX IF NOT EXISTS idx_notifications_recipient_user_id
    ON public.notifications(recipient_user_id);

CREATE INDEX IF NOT EXISTS idx_notifications_recipient_read
    ON public.notifications(recipient_user_id, is_read);

CREATE INDEX IF NOT EXISTS idx_payment_transactions_student_id
    ON public.payment_transactions(student_id);

CREATE INDEX IF NOT EXISTS idx_payment_transactions_tuition_record_id
    ON public.payment_transactions(tuition_record_id);

CREATE INDEX IF NOT EXISTS idx_payment_transactions_status
    ON public.payment_transactions(status);

INSERT INTO public.roles (name, description, created_at)
VALUES
    ('ADMIN', 'System admin', now()),
    ('STUDENT', 'Student role', now()),
    ('LECTURER', 'Lecturer role', now()),
    ('ACADEMIC_ADVISOR', 'Academic advisor role', now())
ON CONFLICT (name) DO NOTHING;
