spring.application.name=backend
server.port=8080

# DATABASE
spring.datasource.url=jdbc:postgresql://localhost:5434/QLSV_db
spring.datasource.username=QLSV_user
spring.datasource.password=QLSV_password
spring.datasource.driver-class-name=org.postgresql.Driver

# FLYWAY
spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=false
spring.flyway.locations=classpath:db/migration

# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.defer-datasource-initialization=false
spring.jpa.open-in-view=false

# JWT
jwt.secret=DayLaMotChuoiBiMatCuaDuAnQLSV2026!@#
